### ISSUE TITLE
Suggestion: add napari explicitly to your dependencies.

### ISSUE THREAD

**Issue by tlambert03** [etasnadi/napari_nucleaizer#2]
While running some tests for [npe2](https://github.com/napari/npe2), this plugin was among those that could not be imported after installation without also manually installing napari.  Even if it may seem obvious that a user of this plugin would already have napari installed, if your package imports anything directly from napari (including, e.g. `napari.types`), then you should add napari to your `install_requires` in setup.cfg/py.

thanks!

**Comment by etasnadi** [comment]
Thanks, I will fix it soon.

**Comment by etasnadi** [comment]
Hi,

I am not sure when I fixed it exactly, but it is fixed in the recent versions at least, so I am planning to close this.

I am also planning to completely eliminate napari from the deps, as a plugin should not directly depend on the host I believe. I see that in my main constructor the viewer instance is "injected" by some background machinery:

`def __init__(self, napari_viewer: "napari.viewer.Viewer", parent: QWidget=None):`

That is good because I can easily mock it and can run tests if I want, or resuse componentst, etc.

I only need napari because I use the `@thread_worker` decorator for the long running bg tasks. Is there any way to accomplish this without explicitly depending on napari? I mean, it could have been injected too. It would be also reasonable if napari would manage a thread pool (resource pooling) and inject thread instances to the plugins when they need it or something similar. What is the best way to accomplish this?

Thanks.

**Comment by tlambert03** [comment]
Great!  Yeah, we do try to generally make it such that you don’t need to import napari. 

> I use the @thread_worker decorator for the long running bg tasks. Is there any way to accomplish this without explicitly depending on napari?

actually most of that logic has been extracted to superqt now (on which napari depends, and simply re-exports that thread worker with a couple minor additions).  See superqt.utils.thread_worker

you can also even just use pure python threading (eg concurrent futures), but the superqt signals make it a bit easier to signal back to the main thread if you need to update the gui (but otherwise, feel free to just use concurrent.futures)

**Comment by etasnadi** [comment]
Thanks, I will consider your suggestions.
